<a href="https://colab.research.google.com/github/AnkitShaw-100/Python-Basics/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
x = [2,3,4,56,67,3]
var = pd.Series(x,index=['a','b','c','d','e','f'])

print(var)
print(type(var))
print(var[3])

a     2
b     3
c     4
d    56
e    67
f     3
dtype: int64
<class 'pandas.core.series.Series'>
56

<ipython-input-4-23bc3e925a3b>:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(var[3])

In [ ]:
dic = {"name":['Python','C','C++','Java'], "por":[10,11,22,33], "rank":[2,1,3,4]}
var1 = pd.Series(dic)
var1

name    [Python, C, C++, Java]
por           [10, 11, 22, 33]
rank              [2, 1, 3, 4]
dtype: object

In [ ]:
s = pd.Series(12,index=[1,2,3,4,5,6])
print(s)
print(type(s))

1    12
2    12
3    12
4    12
5    12
6    12
dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
s1 = pd.Series(12,index=[1,2,3,4,5,6])
s2 = pd.Series(12,index=[1,2,3,4])
print(s1+s2)

1    24.0
2    24.0
3    24.0
4    24.0
5     NaN
6     NaN
dtype: float64

In [ ]:
l = [1,2,3,4,5,6]
var = pd.DataFrame(l)
print(type(var))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
d = {"c1":[1,2,3,4,5], "c2": [5,4,3,2,1]}
var = pd.DataFrame(d)
var1 = pd.DataFrame(d,index=['a','b','c','d','e'])
var2 = pd.DataFrame(d,columns=['c1'])
print(var)
print(var1)
print(var2)
print(type(var))

   c1  c2
0   1   5
1   2   4
2   3   3
3   4   2
4   5   1
   c1  c2
a   1   5
b   2   4
c   3   3
d   4   2
e   5   1
   c1
0   1
1   2
2   3
3   4
4   5
<class 'pandas.core.frame.DataFrame'>

In [ ]:
list_1 = [[1,2,3,4,5],[11,12,13,14,15]]

var = pd.DataFrame(list_1)

print(type(var))
print(var)

<class 'pandas.core.frame.DataFrame'>
    0   1   2   3   4
0   1   2   3   4   5
1  11  12  13  14  15

In [ ]:
var = pd.DataFrame({"A":[1,2,3,4], "B":[5,6,7,8]})
var = pd.DataFrame(var)
print(var)

   A  B
0  1  5
1  2  6
2  3  7
3  4  8

In [ ]:
var["C"] = var["A"]+var["B"]
print(var)

   A  B   C
0  1  5   6
1  2  6   8
2  3  7  10
3  4  8  12

In [ ]:
var["C"] = var["A"]-var["B"]
print(var)

   A  B  C
0  1  5 -4
1  2  6 -4
2  3  7 -4
3  4  8 -4

In [ ]:
var["C"] = var["A"]*var["B"]
print(var)

   A  B   C
0  1  5   5
1  2  6  12
2  3  7  21
3  4  8  32

In [ ]:
var["C"] = var["A"]/var["B"]
print(var)

   A  B         C
0  1  5  0.200000
1  2  6  0.333333
2  3  7  0.428571
3  4  8  0.500000

In [ ]:
var["Python"] = var["C"] <= 2

print(var1)

   c1  c2  Pyhton
a   1   5    True
b   2   4    True
c   3   3    True
d   4   2    True
e   5   1    True

In [ ]:
var = pd.DataFrame({"A":[1,2,3,4], "B":[5,6,7,8]})
print(var)
var.insert(1,"AB",var["A"])
print(var)
var.insert(1,"BA",var["B"])
print(var)
var.pop("BA")
print(var)
var.pop("AB")
print(var)

   A  B
0  1  5
1  2  6
2  3  7
3  4  8
   A  AB  B
0  1   1  5
1  2   2  6
2  3   3  7
3  4   4  8
   A  BA  AB  B
0  1   5   1  5
1  2   6   2  6
2  3   7   3  7
3  4   8   4  8
   A  AB  B
0  1   1  5
1  2   2  6
2  3   3  7
3  4   4  8
   A  B
0  1  5
1  2  6
2  3  7
3  4  8

In [ ]:
dis = {"a":[1,2,3,4,5],"b":[6,7,8,9,10],"c":[11,12,13,14,1]}
var = pd.DataFrame(dis)
print(var)
var.to_csv("test.csv")

   a   b   c
0  1   6  11
1  2   7  12
2  3   8  13
3  4   9  14
4  5  10   1

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
file_path = "/content/drive/My Drive/annual_report.csv"

csv_1 = pd.read_csv(file_path)
# display(csv_1)
csv_2 = pd.read_csv(file_path, nrows=7,usecols=["Industry_aggregation_NZSIOC","Industry_name_NZSIOC"])
display(csv_2)
# csv_1.describe()
# csv_1.head(10)
# # csv_1.tail(5)
# csv_1.index.array  index -> array
import numpy as np
# v = np.asarray(csv_1)
csv_1.sort_index(axis=0,ascending = False)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

  Industry_aggregation_NZSIOC Industry_name_NZSIOC
0                     Level 1       All industries
1                     Level 1       All industries
2                     Level 1       All industries
3                     Level 1       All industries
4                     Level 1       All industries
5                     Level 1       All industries
6                     Level 1       All industries

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
50984,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
50983,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
50982,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
50981,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
50980,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
...,...,...,...,...,...,...,...,...,...,...
4,2023,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,832964,ANZSIC06 divisions A-S (excluding classes K633...
3,2023,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25010,ANZSIC06 divisions A-S (excluding classes K633...
2,2023,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,84354,ANZSIC06 divisions A-S (excluding classes K633...
1,2023,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,821630,ANZSIC06 divisions A-S (excluding classes K633...
0,2023,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,930995,ANZSIC06 divisions A-S (excluding classes K633...